services:
  todo-app:
    image: 0marmohamed/fortstak-todo-list-devops-assessment:latest
    container_name: fortstak-todo-app
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - .env
    environment:
      - mongoDbUrl=${mongoDbUrl}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    restart: always